spring.application.name=demo

server.port=8083

spring.profiles.active=local

logging.level.root=INFO
logging.level.com.example.demo2: DEBUG

spring.datasource.url=jdbc:mysql://localhost:3306/community_db
spring.datasource.username=root
spring.datasource.password=Swd20041231
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=myveryveryveryverysecuresecretkey123456
jwt.expiration=86400000
